### ISSUE TITLE
ImportError: libboost_python-py34.so.1.55.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zaheer308** [Azure/azure-iot-sdk-python#128]
## OS and version used: 
raspbian
## Python runtime used: 
python3.5
### SDK version used

**# Description of the issue:**
Installation was performed based off of the above environment as:
sudo apt-get install libpython3-dev
sudo apt-get install libboost-python-dev
sudo pip install azure-iothub-service-client
sudo pip3 install azure-iothub-service-client

Once after that, using service SDK by importing in Python it fails with error: ImportError: libboost_python-py34.so.1.54.0: cannot open shared object file: No such file or directory

Effectively cannot use Python SDK.

**# Code sample exhibiting the issue:**
import iothub_service_client 

**# Console log of the issue:
From the Python console:**

`import iothub_service_client

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libboost_python-py34.so.1.55.0: cannot open shared object file: No such file or directory
>>> ImportError: libboost_python-py34.so.1.55.0: cannot open shared object file: No such file or directory
`

**Comment by zolvarga** [comment]
@zaheer308 

Install boost with the following commands:

sudo apt-get install libboost1.55-all
OR
sudo apt-get install libboost-all-dev
OR
sudo apt-get update
sudo apt-get upgrade

Best Regards,
Zoltan

**Comment by kaareseras** [comment]
Running in a docker python:3.5 I hav copied the files

iothub_client_prov_args.py        iothub_client_sample_x509.py
iothub_client_args.py         iothub_client_prov_hsm_sample.py  iothub_client_shared_transport_sample.py
iothub_client_cert.py         iothub_client_sample.py           readme.md
iothub_client_file_upload.py  iothub_client_sample_class.py

run the install: pip install azure-iothub-device-client
and sudo apt-get install libboost1.55-all
and apt-get update
and apt-get upgrade

but when running the iothub_client_sample.py i still get this error:

python iothub_client_sample.py
Traceback (most recent call last):
  File "iothub_client_sample.py", line 10, in <module>
    import iothub_client
  File "/usr/local/lib/python3.5/site-packages/iothub_client/__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: libboost_python-py35.so.1.58.0: cannot open shared object file: No such file or directory

Any idea of how to get this to work

**Comment by cueBall123** [comment]
I am running this on CENTOS 7 . I've also install boost packages. But getting the same import error with boost error. Documentation doesn't say anything about how to setup boost.

**Comment by pierreca** [comment]
@zaheer308 @martinabbott @kaareseras  usually these problems appear when the default version of boost on the system is different from the one we link the SDK against. I just published a new version of the packages (1.4.1) that builds against the default raspbian stretch version - all of you working with raspbian should be good now. can you please confirm?

@cueBall123 not sure which version of boost comes with the version of CENTOS 7 but you might be better of building from scratch.  the instructions are here:
https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md

**Comment by pierreca** [comment]
closing after some inactivity - we believe this has been answered. feel free to reopen or open a new issue if the problem persists.

**Comment by az-iot-builder-01** [comment]
@zaheer308, @martinabbott, @kaareseras, @cueBall123, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)

**Comment by drcrook1** [comment]
I'm putting a python module inside of a container which takes a dependency on this and hitting it as well.  I've based off of the latest miniconda3 container; which leverages python 3.7.  I can set python back to a different version and have set it to 3.5 and install the libboost-dev-all.

I still get the same error:

>>> import iothub_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.5/site-packages/iothub_client/__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: libboost_python-py35.so.1.58.0: cannot open shared object file: No such file or directory

**Comment by mibrl12** [comment]
@drcrook1 Same problem here.

**Comment by MLsmaller** [comment]
> m running this on CENTOS 7 . I've also install boost packages. But getting the same import error with boost error. Documentation doesn't say anything about how to setup boost.

Hello, I have the same problem as you. How do you solve it? I sincerely hope to get your reply

**Comment by georgegoglodze** [comment]
Same problem here

**Comment by kingkashyap** [comment]
Even I am facing the same issue, I have installed "boost" modules using:
sudo apt-get install libboost-all-dev 

which have installed many files.....but the error persists
also i have installed 
sudo apt-get install libcurl3

my current version of libboost is 1.65.1.0.ubuntu1
found this by using the command 

dpkg -s libboost-dev | grep 'Version'

This is the error what i get:

Traceback (most recent call last):
  File "main.py", line 16, in <module>
    import iothub_client
  File "/home/subbaramar/.local/lib/python3.6/site-packages/iothub_client/__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: libboost_python-py35.so.1.58.0: cannot open shared object file: No such file or directory

**Comment by elyancorrea** [comment]
Same problem.
Python: 3.6.9

I've did all solutions.
